dict_ressource = {
    "ressource_actuelle": 0,
    "ressource_total":0,
    "machine":0,
    "prod_base_machine": 0.3,
    "multiplicateur_cout_machine": 1.35,
    "machinelv2": 0,
    "prod_base_machinelv2": 2,
    "multiplicateur_cout_machine": 1.38,
    "machinelv3":0,
    "prod_base_machinelv3": 30,
    "multiplicateur_cout_machine": 1.41,
    "machinelv4":0,
    "prod_base_machinelv4": 300,
    "multiplicateur_cout_machine": 1.43,
    "machinelv5":0,
    "prod_base_machinelv5": 3000,
    "multiplicateur_cout_machinelv5": 1.47,
    "cout-base-machinelv5": 20000,
    "cout-base-machinelv4": 8500,
    "cout-base-machinelv3": 1500,
    "cout-base-machinelv2": 100,
    "cout-base-machine": 10,
    "tick-rate":100,
}